<a href="https://colab.research.google.com/github/ansariwaleed/D2L-diving-into-deep-learning-/blob/main/D2L_day2_pg_38.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data preprcessing

In [ ]:
#2.2.1 Reading the dataset

import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')


In [ ]:
#lets import data using read.csv
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


In [ ]:
#2.2.2 Data Preparation

inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na = True)
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True


In [ ]:
#for missing values, replace NaN with mean values

inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True


In [ ]:
#2.2.3 cnversion to the tensor format

import torch

X = torch.tensor(inputs.to_numpy(dtype= float))
y = torch.tensor(targets.to_numpy(dtype=float))

X,y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

#2.3.2 vectors

In [ ]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [ ]:
x[1]

tensor(1)

In [ ]:
len(x)

3

In [ ]:
x.shape

torch.Size([3])

#2.3.3 Matrices

In [ ]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
#Transpose of matrix A
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [ ]:
# recheck the values of matrices
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

#2.3.4 Tensors

In [ ]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

##Basic properties of Tensor Arithmatic

In [ ]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)


(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [25]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone()
A, A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [26]:
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [27]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

##2.3.6 Reduction

In [29]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [33]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [30]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [31]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [32]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [34]:
A.sum(axis=[0, 1]) == A.sum() # Same as A.sum()

tensor(True)

In [36]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [37]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [39]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [38]:
## 2.3.7 Non-Reduction Sum

sum_A = A.sum(axis=1, keepdims= True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [40]:
A/ sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [41]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [42]:
#2.3.8 Dot Product

y = torch.ones(3, dtype = torch.float32)
x,y, torch.dot(x,y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [44]:
torch.sum(x)

tensor(3.)

In [43]:
torch.sum(x * y) # same as sum(x) coz y is all ones

tensor(3.)

## Matrix-Vector product

In [46]:
A.shape, x.shape, torch.mv(A, x), A@x #we can siply use

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

##2.3.10 Matrix-Matrix Mutliplication

In [49]:
B = torch.ones(3,4)
torch.mm(A,B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

##2.3.11 Norms

###helps to quatify the magnitude of a matrix
>mostly taking sum of squares of all the elements and then taking sqaure root

In [52]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [53]:
torch.abs(u).sum()

tensor(7.)

In [54]:
torch.norm(torch.ones((4,9)))

tensor(6.)